import { useState } from 'react';
import { 
  FileText, 
  Layers, 
  AlertCircle, 
  CheckCircle2, 
  Clock, 
  ShieldAlert, 
  Send, 
  Check, 
  Printer, 
  Download, 
  RefreshCw, 
  Bell, 
  Lock,
  User,
  Building,
  Calendar,
  Eye,
  FileCheck
} from 'lucide-react';
import CommentLayer from '../../components/feedback/CommentLayer';
import './TreasuryCreatorPDAcclosureScreen.css';

// Initial Mock Claims (Approved by FD, reflecting at Treasury Creator)
interface Claim {
  id: string;
  accountNo: string;
  accountName: string;
  dept: string;
  balance: number;
  approvedDate: string;
  scheme: string;
  status: 'approved_claim' | 'bill_draft' | 'bill_submitted' | 'completed';
  billNo?: string;
  voucherNo?: string;
  challanNo?: string;
  challanStatus?: 'Active' | 'Used / Consumed';
  originalExpHeads: { head: string; amount: number; receiptHoA: string }[];
}

const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'CLM-2026-9912',
    accountNo: 'PD-500-022021-8201-1001',
    accountName: 'Urban Administration',
    dept: 'Urban Development',
    balance: 5000000,
    approvedDate: '2026-05-18',
    scheme: 'SCH-LPS-2026-01',
    status: 'approved_claim',
    originalExpHeads: [
      { head: '2202-01-101-0001', amount: 3000000, receiptHoA: '0070-60-800' },
      { head: '2215-02-800-0002', amount: 2000000, receiptHoA: '0070' } // Fallback to 0070
    ]
  },
  {
    id: 'CLM-2026-4831',
    accountNo: 'PD-400-112020-4932-1002',
    accountName: 'Rural Development',
    dept: 'Rural Development',
    balance: 13100000,
    approvedDate: '2026-05-20',
    scheme: 'SCH-LPS-2026-02',
    status: 'approved_claim',
    originalExpHeads: [
      { head: '2515-00-101-0001', amount: 13100000, receiptHoA: '0070-60-800' }
    ]
  }
];

const NOTIFICATIONS = [
  { id: 1, type: 'claim_gen', text: 'Notification: Approved closure claim CLM-2026-9912 generated by FD for PD-500-022021-8201-1001.', recipient: 'Treasury Officer & Deposit Admin', time: '2026-05-18 11:32 AM' },
  { id: 2, type: 'claim_gen', text: 'Notification: Approved closure claim CLM-2026-4831 generated by FD for PD-400-112020-4932-1002.', recipient: 'Treasury Officer & Deposit Admin', time: '2026-05-20 11:46 AM' },
  { id: 3, type: 'bill_submit', text: 'System Log: By-transfer bill generated and submitted to Treasury Officer (Approver) queue.', recipient: 'Treasury Officer (Approver)', time: 'Pending Action' },
  { id: 4, type: 'auto_sys', text: 'System Action: By-transfer challan auto-marked as Used / Consumed. Refund functionality blocked. Account Closure Voucher generated.', recipient: 'Deposit Admin & Auditor', time: 'Pending Approval' }
];

type TabType = 'claims' | 'bills' | 'vouchers' | 'notifications';

export default function TreasuryCreatorPDAcclosureScreen() {
  const [activeTab, setActiveTab] = useState<TabType>('claims');
  const [claims, setClaims] = useState<Claim[]>(INITIAL_CLAIMS);
  const [selectedClaimId, setSelectedClaimId] = useState<string | null>(null);
  const [logs, setLogs] = useState(NOTIFICATIONS);

  // Bill creation form state
  const [customRemarks, setCustomRemarks] = useState('');

  // Selected claim object helper
  const selectedClaim = claims.find(c => c.id === selectedClaimId);

  // Helper to format currency
  const fmt = (val: number) => '₹ ' + val.toLocaleString('en-IN');

  // Trigger Bill Generation (Creator workflow)
  const handleGenerateBill = (claimId: string) => {
    setClaims(prev => prev.map(claim => {
      if (claim.id === claimId) {
        return {
          ...claim,
          status: 'bill_submitted',
          billNo: `BIL-BY-TR-${claim.id.split('-')[2]}-${Math.floor(1000 + Math.random() * 9000)}`,
          challanNo: `BT-CH-2026-${Math.floor(1000 + Math.random() * 9000)}`,
          challanStatus: 'Active'
        };
      }
      return claim;
    }));

    // Update Logs
    setLogs(prev => prev.map(log => {
      if (log.type === 'bill_submit') {
        return { ...log, time: new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }) };
      }
      return log;
    }));

    setCustomRemarks('');
    setActiveTab('bills');

    alert('By-transfer bill generated successfully and submitted to the Treasury Officer (Approver) for final approval.');
  };

  // Simulating the Treasury Officer's Approval of the bill
  const handleSimulateTOApproval = (claimId: string) => {
    setClaims(prev => prev.map(claim => {
      if (claim.id === claimId) {
        return {
          ...claim,
          status: 'completed',
          challanStatus: 'Used / Consumed', // Auto-marks challan as used/consumed after approval
          voucherNo: `ACV-2026-${claim.id.split('-')[2]}` // Generates account closure voucher
        };
      }
      return claim;
    }));

    // Update Logs
    setLogs(prev => prev.map(log => {
      if (log.type === 'auto_sys') {
        return { ...log, time: new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }) };
      }
      return log;
    }));

    alert('SUCCESS:\n1. Treasury Officer approved the bill.\n2. By-transfer challan auto-marked as "Used / Consumed".\n3. Refund functionality blocked for this account.\n4. Account Closure Voucher generated.');
  };

  // Status counters
  const approvedClaimsCount = claims.filter(c => c.status === 'approved_claim').length;
  const activeBillsCount = claims.filter(c => c.status === 'bill_submitted').length;
  const completedCount = claims.filter(c => c.status === 'completed').length;

  return (
    <CommentLayer screenId="sprint3-story4-treasury-creator-pd-account-closure" moduleName="deposit">
      <div className="tcc-screen animate-fade-in">
        
        {/* Header */}
        <header>
          <h1>PD Account Closure & Bill Generation (Treasury Creator)</h1>
          <p className="header-desc">
            Process FD-approved PD-CF closure claims. Map original expenditure heads to receipt HoAs, generate by-transfer bills, track Treasury Officer approvals, block refunds, and review finalized Account Closure Vouchers.
          </p>
          <div className="tcc-header-badges">
            <span className="tcc-header-badge role"><User size={12} /> Treasury Officer (Creator)</span>
            <span className="tcc-header-badge module"><Building size={12} /> Treasury Treasury Creator Workflow</span>
            <span className="tcc-header-badge fy"><Calendar size={12} /> FY 2026-27</span>
          </div>
        </header>

        {/* Stats Dashboard */}
        <div className="tcc-stats-grid">
          <div className="tcc-stat-card primary">
            <div className="tcc-stat-icon primary"><Layers size={20} /></div>
            <div className="tcc-stat-info">
              <span className="tcc-stat-value">{claims.length}</span>
              <span className="tcc-stat-label">Total Claims Evaluated</span>
            </div>
          </div>
          <div className="tcc-stat-card warning">
            <div className="tcc-stat-icon warning"><Clock size={20} /></div>
            <div className="tcc-stat-info">
              <span className="tcc-stat-value">{approvedClaimsCount}</span>
              <span className="tcc-stat-label">Pending Bill Generation</span>
            </div>
          </div>
          <div className="tcc-stat-card info">
            <div className="tcc-stat-icon info"><RefreshCw className="spin-hover" size={20} /></div>
            <div className="tcc-stat-info">
              <span className="tcc-stat-value">{activeBillsCount}</span>
              <span className="tcc-stat-label">Submitted to TO (Approver)</span>
            </div>
          </div>
          <div className="tcc-stat-card success">
            <div className="tcc-stat-icon success"><CheckCircle2 size={20} /></div>
            <div className="tcc-stat-info">
              <span className="tcc-stat-value">{completedCount}</span>
              <span className="tcc-stat-label">Accounts Fully Closed</span>
            </div>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="tcc-tabs">
          <button 
            className={`tcc-tab ${activeTab === 'claims' ? 'active' : ''}`}
            onClick={() => { setActiveTab('claims'); setSelectedClaimId(null); }}
          >
            <Layers size={16} /> Approved Claims from FD
            {approvedClaimsCount > 0 && <span className="tcc-tab-count">{approvedClaimsCount}</span>}
          </button>
          <button 
            className={`tcc-tab ${activeTab === 'bills' ? 'active' : ''}`}
            onClick={() => { setActiveTab('bills'); setSelectedClaimId(null); }}
          >
            <FileText size={16} /> Active Bills Tracker
            {activeBillsCount > 0 && <span className="tcc-tab-count">{activeBillsCount}</span>}
          </button>
          <button 
            className={`tcc-tab ${activeTab === 'vouchers' ? 'active' : ''}`}
            onClick={() => { setActiveTab('vouchers'); setSelectedClaimId(null); }}
          >
            <FileCheck size={16} /> Account Closure Vouchers
            {completedCount > 0 && <span className="tcc-tab-count">{completedCount}</span>}
          </button>
          <button 
            className={`tcc-tab ${activeTab === 'notifications' ? 'active' : ''}`}
            onClick={() => { setActiveTab('notifications'); setSelectedClaimId(null); }}
          >
            <Bell size={16} /> Notifications & System Logs
          </button>
        </div>

        {/* ────────────────── TAB 1: APPROVED CLAIMS ────────────────── */}
        {activeTab === 'claims' && (
          <div className="grid-layout">
            <div className="tcc-section">
              <div className="tcc-section-header">
                <div className="tcc-section-icon"><Layers size={18} /></div>
                <h2>Approved PD-CF Closure Claims Queue</h2>
              </div>
              <div className="tcc-section-body" style={{ padding: 0 }}>
                <div className="tcc-info-callout info" style={{ margin: 'var(--space-4)' }}>
                  <AlertCircle size={16} />
                  <div>
                    The following PD account closure claims have been approved by the Finance Department. 
                    Generate the <strong>By-Transfer Bill</strong> below to execute the central transfer of funds from original expenditure heads to respective receipt heads.
                  </div>
                </div>

                <div className="tcc-table-wrapper" style={{ border: 'none' }}>
                  <table className="tcc-table">
                    <thead>
                      <tr>
                        <th>Claim ID</th>
                        <th>PD Account Number</th>
                        <th>Account Name</th>
                        <th>Department</th>
                        <th className="align-right">Total Closed Amount</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {claims.filter(c => c.status === 'approved_claim').length === 0 ? (
                        <tr>
                          <td colSpan={6} style={{ textAlign: 'center', color: 'var(--color-text-tertiary)', padding: 'var(--space-8)' }}>
                            No pending closure claims reflecting in Treasury Creator queue.
                          </td>
                        </tr>
                      ) : (
                        claims.filter(c => c.status === 'approved_claim').map(claim => (
                          <tr 
                            key={claim.id} 
                            className={`row-clickable ${selectedClaimId === claim.id ? 'selected' : ''}`}
                            onClick={() => setSelectedClaimId(claim.id)}
                          >
                            <td style={{ fontWeight: 700, color: 'var(--color-primary)' }}>{claim.id}</td>
                            <td style={{ fontFamily: 'monospace', fontWeight: 600 }}>{claim.accountNo}</td>
                            <td>{claim.accountName}</td>
                            <td>{claim.dept}</td>
                            <td className="align-right" style={{ fontWeight: 700, color: 'var(--color-text-primary)' }}>{fmt(claim.balance)}</td>
                            <td>
                              <button 
                                className="btn btn-sm btn-primary"
                                onClick={(e) => { e.stopPropagation(); setSelectedClaimId(claim.id); }}
                              >
                                View Details & Generate
                              </button>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* Bill Generation Details Panel */}
            {selectedClaim && selectedClaim.status === 'approved_claim' && (
              <div className="tcc-bill-grid animate-fade-in-up">
                
                {/* original expenditure details */}
                <div className="tcc-panel-card">
                  <div className="tcc-panel-title">
                    <ShieldAlert size={16} /> Original Expenditure & Receipt HoA Mapping
                  </div>
                  <p style={{ fontSize: '13px', color: 'var(--color-text-secondary)', marginBottom: 'var(--space-4)' }}>
                    System identifies original expenditure heads and maps them to respective receipt HoAs with a fallback default to <strong>0070</strong>.
                  </p>

                  <div className="tcc-table-wrapper">
                    <table className="tcc-table" style={{ margin: 0 }}>
                      <thead>
                        <tr>
                          <th>Original Expenditure Head</th>
                          <th>Receipt HoA Mapping</th>
                          <th className="align-right">Budget Line Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        {selectedClaim.originalExpHeads.map((exp, idx) => (
                          <tr key={idx}>
                            <td style={{ fontFamily: 'monospace', fontWeight: 500 }}>{exp.head}</td>
                            <td>
                              <span className="tcc-badge approved" style={{ fontFamily: 'monospace' }}>
                                {exp.receiptHoA === '0070' ? '0070 (Default Receipt)' : exp.receiptHoA}
                              </span>
                            </td>
                            <td className="align-right" style={{ fontWeight: 600 }}>{fmt(exp.amount)}</td>
                          </tr>
                        ))}
                        <tr style={{ background: 'var(--color-bg-secondary)', fontWeight: 700 }}>
                          <td colSpan={2}>Total Amount By-Transfer:</td>
                          <td className="align-right" style={{ color: 'var(--color-primary)' }}>{fmt(selectedClaim.balance)}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div className="tcc-info-callout warning" style={{ marginTop: 'var(--space-4)' }}>
                    <Lock size={16} />
                    <div>
                      <strong>System Block Enforced:</strong> Refund capabilities for PD account <strong>{selectedClaim.accountNo}</strong> will be permanently disabled upon final Treasury Officer approval of this by-transfer bill.
                    </div>
                  </div>
                </div>

                {/* bill submission form */}
                <div className="tcc-panel-card">
                  <div className="tcc-panel-title">
                    <FileText size={16} /> Generate By-Transfer Bill
                  </div>
                  
                  <div className="tcc-detail-row">
                    <span>Account Number:</span>
                    <span>{selectedClaim.accountNo}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>Account Holder:</span>
                    <span>{selectedClaim.accountName}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>Approved Claim ID:</span>
                    <span style={{ color: 'var(--color-primary)' }}>{selectedClaim.id}</span>
                  </div>
                  <div className="tcc-detail-row" style={{ borderTop: '1px dashed var(--color-border-light)', paddingTop: 'var(--space-2)', marginTop: 'var(--space-2)' }}>
                    <span>Transfer Bill Amount:</span>
                    <span style={{ color: 'var(--color-success)', fontSize: '15px' }}>{fmt(selectedClaim.balance)}</span>
                  </div>

                  <div className="tcc-action-panel">
                    <div className="form-group">
                      <label className="form-label">Treasury Creator Remarks <span className="required">*</span></label>
                      <textarea 
                        className="form-input" 
                        placeholder="Enter remarks for the Treasury Officer (Approver) e.g., PD closure by-transfer bill generated in accordance with FD Order."
                        rows={3}
                        value={customRemarks}
                        onChange={(e) => setCustomRemarks(e.target.value)}
                      />
                    </div>

                    <button 
                      className="btn btn-primary"
                      disabled={!customRemarks.trim()}
                      onClick={() => handleGenerateBill(selectedClaim.id)}
                      style={{ width: '100%', padding: 'var(--space-3)' }}
                    >
                      <Send size={16} /> Generate & Submit By-Transfer Bill
                    </button>
                  </div>
                </div>

              </div>
            )}
          </div>
        )}

        {/* ────────────────── TAB 2: ACTIVE BILLS TRACKER ────────────────── */}
        {activeTab === 'bills' && (
          <div className="grid-layout animate-fade-in">
            
            {/* Simulation Sandbox Panel */}
            {claims.some(c => c.status === 'bill_submitted') && (
              <div className="tcc-approver-sandbox">
                <div className="tcc-sandbox-header">
                  <ShieldAlert size={20} /> 
                  <span>Stakeholder Testing & Validation Sandbox</span>
                </div>
                <div className="tcc-sandbox-desc">
                  This simulated control panel allows stakeholders to act as the <strong>Treasury Officer (Approver)</strong>. 
                  Approving a bill executes critical, automated background steps defined in Step 4A.
                </div>
                <div style={{ display: 'flex', gap: 'var(--space-3)', flexWrap: 'wrap' }}>
                  {claims.filter(c => c.status === 'bill_submitted').map(claim => (
                    <button 
                      key={claim.id}
                      className="btn btn-primary"
                      onClick={() => handleSimulateTOApproval(claim.id)}
                      style={{ background: 'linear-gradient(135deg, #b45309 0%, #d97706 100%)', border: 'none' }}
                    >
                      <CheckCircle2 size={14} /> Approve Bill for {claim.id} as TO (Approver)
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div className="tcc-section">
              <div className="tcc-section-header">
                <div className="tcc-section-icon"><FileText size={18} /></div>
                <h2>Submitted By-Transfer Bills & Approver Status</h2>
              </div>
              
              <div className="tcc-section-body" style={{ padding: 0 }}>
                <table className="tcc-table">
                  <thead>
                    <tr>
                      <th>Bill Number</th>
                      <th>Claim Reference</th>
                      <th>PD Account</th>
                      <th>By-Transfer Challan</th>
                      <th>Challan Status</th>
                      <th className="align-right">Bill Value</th>
                      <th>Approver Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {claims.filter(c => c.status === 'bill_submitted' || c.status === 'completed').length === 0 ? (
                      <tr>
                        <td colSpan={8} style={{ textAlign: 'center', color: 'var(--color-text-tertiary)', padding: 'var(--space-8)' }}>
                          No active or approved by-transfer bills found. Generate a bill under the "Approved Claims" tab first.
                        </td>
                      </tr>
                    ) : (
                      claims.filter(c => c.status === 'bill_submitted' || c.status === 'completed').map(claim => (
                        <tr key={claim.id} className={selectedClaimId === claim.id ? 'selected' : ''} onClick={() => setSelectedClaimId(claim.id)}>
                          <td style={{ fontWeight: 700 }}>{claim.billNo || 'Generating...'}</td>
                          <td style={{ color: 'var(--color-text-secondary)', fontWeight: 500 }}>{claim.id}</td>
                          <td style={{ fontFamily: 'monospace' }}>{claim.accountNo}</td>
                          <td style={{ fontFamily: 'monospace', fontWeight: 600 }}>{claim.challanNo}</td>
                          <td>
                            <span className={`tcc-badge ${claim.challanStatus === 'Used / Consumed' ? 'consumed' : 'pending'}`}>
                              {claim.challanStatus === 'Used / Consumed' ? 'Used / Consumed' : 'Active (Unused)'}
                            </span>
                          </td>
                          <td className="align-right" style={{ fontWeight: 700 }}>{fmt(claim.balance)}</td>
                          <td>
                            {claim.status === 'completed' ? (
                              <span className="tcc-badge approved"><CheckCircle2 size={12} /> Approved by TO</span>
                            ) : (
                              <span className="tcc-badge pending"><Clock size={12} /> Pending TO Approval</span>
                            )}
                          </td>
                          <td>
                            <button 
                              className="btn btn-sm btn-secondary"
                              onClick={(e) => { e.stopPropagation(); setSelectedClaimId(claim.id); }}
                            >
                              <Eye size={12} /> View Lifecycle
                            </button>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Bill Details & Interactive Lifecycle Tracker */}
            {selectedClaim && (selectedClaim.status === 'bill_submitted' || selectedClaim.status === 'completed') && (
              <div className="tcc-bill-grid animate-fade-in-up">
                
                {/* Details Card */}
                <div className="tcc-panel-card">
                  <div className="tcc-panel-title">
                    <FileText size={16} /> By-Transfer Bill Details
                  </div>
                  <div className="tcc-detail-row">
                    <span>Bill Reference Number:</span>
                    <span>{selectedClaim.billNo}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>Associated Challan:</span>
                    <span style={{ fontFamily: 'monospace' }}>{selectedClaim.challanNo}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>Original Account:</span>
                    <span>{selectedClaim.accountNo}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>Associated Dept:</span>
                    <span>{selectedClaim.dept}</span>
                  </div>
                  <div className="tcc-detail-row">
                    <span>By-Transfer Amount:</span>
                    <span style={{ color: 'var(--color-primary)', fontWeight: 700 }}>{fmt(selectedClaim.balance)}</span>
                  </div>
                  
                  <hr style={{ border: 'none', borderTop: '1px dashed var(--color-border-light)', margin: 'var(--space-4) 0' }} />

                  {/* System State Block Indicators */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 'var(--space-2) var(--space-3)', background: 'var(--color-bg)', borderRadius: 'var(--radius-md)' }}>
                      <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--color-text-secondary)' }}>Refund Functionality:</span>
                      {selectedClaim.status === 'completed' ? (
                        <span className="tcc-badge blocked"><Lock size={12} /> Locked / Blocked</span>
                      ) : (
                        <span className="tcc-badge pending">Enabled</span>
                      )}
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 'var(--space-2) var(--space-3)', background: 'var(--color-bg)', borderRadius: 'var(--radius-md)' }}>
                      <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--color-text-secondary)' }}>Account Closure Voucher:</span>
                      {selectedClaim.status === 'completed' ? (
                        <span className="tcc-badge approved" style={{ fontWeight: 600 }}>{selectedClaim.voucherNo}</span>
                      ) : (
                        <span className="tcc-badge draft">Pending Approval</span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Workflow Stepper */}
                <div className="tcc-panel-card">
                  <div className="tcc-panel-title">
                    <RefreshCw size={16} /> Bill Lifecycle & Automated System Workflows
                  </div>
                  
                  <div className="tcc-timeline">
                    <div className="tcc-timeline-item completed">
                      <div className="tcc-timeline-dot" />
                      <div className="tcc-timeline-content">
                        <span className="tcc-timeline-title">1. Original Exp Head & Receipt HoA Identified</span>
                        <span className="tcc-timeline-desc">Mappped to receipt heads with 0070 fallback logic applied.</span>
                      </div>
                    </div>

                    <div className="tcc-timeline-item completed">
                      <div className="tcc-timeline-dot" />
                      <div className="tcc-timeline-content">
                        <span className="tcc-timeline-title">2. Closure Claim Approved by FD</span>
                        <span className="tcc-timeline-desc">Approved claim reflecting at Treasury Creator queue.</span>
                      </div>
                    </div>

                    <div className={`tcc-timeline-item ${selectedClaim.status === 'bill_submitted' ? 'active' : 'completed'}`}>
                      <div className="tcc-timeline-dot" />
                      <div className="tcc-timeline-content">
                        <span className="tcc-timeline-title">3. By-Transfer Bill Generated by Treasury Creator</span>
                        <span className="tcc-timeline-desc">Bill {selectedClaim.billNo} generated and sent to TO for approval.</span>
                      </div>
                    </div>

                    <div className={`tcc-timeline-item ${selectedClaim.status === 'completed' ? 'completed' : 'active'}`}>
                      <div className="tcc-timeline-dot" />
                      <div className="tcc-timeline-content">
                        <span className="tcc-timeline-title">4. Bill Approved by Treasury Officer</span>
                        <span className="tcc-timeline-desc">Requires final digital approval from the Treasury Approver.</span>
                      </div>
                    </div>

                    <div className={`tcc-timeline-item ${selectedClaim.status === 'completed' ? 'completed' : ''}`}>
                      <div className="tcc-timeline-dot" />
                      <div className="tcc-timeline-content">
                        <span className="tcc-timeline-title">5. Automated System Actions Executed</span>
                        <span className="tcc-timeline-desc">
                          Challan marked as Used/Consumed, Refunds Blocked, and Account Closure Voucher generated.
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            )}
          </div>
        )}

        {/* ────────────────── TAB 3: ACCOUNT CLOSURE VOUCHERS ────────────────── */}
        {activeTab === 'vouchers' && (
          <div className="grid-layout animate-fade-in">
            <div className="tcc-section">
              <div className="tcc-section-header">
                <div className="tcc-section-icon"><FileCheck size={18} /></div>
                <h2>Account Closure Vouchers & Ledgers (Central System)</h2>
              </div>
              <div className="tcc-section-body" style={{ padding: 0 }}>
                <div className="tcc-info-callout success" style={{ margin: 'var(--space-4)' }}>
                  <CheckCircle2 size={16} />
                  <div>
                    The following PD-CF accounts have been fully closed. The system has automatically generated an 
                    <strong> Account Closure Voucher</strong> representing the by-transfer double-entry impact in the treasury ledger, and has permanently blocked refund functionalities.
                  </div>
                </div>

                <table className="tcc-table">
                  <thead>
                    <tr>
                      <th>Voucher ID</th>
                      <th>Associated Bill No.</th>
                      <th>PD Account Closed</th>
                      <th>Account Name</th>
                      <th>By-Transfer Challan</th>
                      <th className="align-right">Closed Amount</th>
                      <th>Refund Status</th>
                      <th>Voucher</th>
                    </tr>
                  </thead>
                  <tbody>
                    {claims.filter(c => c.status === 'completed').length === 0 ? (
                      <tr>
                        <td colSpan={8} style={{ textAlign: 'center', color: 'var(--color-text-tertiary)', padding: 'var(--space-8)' }}>
                          No closed accounts or generated closure vouchers found. 
                          Complete the bill workflow under the "Active Bills Tracker" tab to execute closure and generate vouchers.
                        </td>
                      </tr>
                    ) : (
                      claims.filter(c => c.status === 'completed').map(claim => (
                        <tr 
                          key={claim.id} 
                          className={`row-clickable ${selectedClaimId === claim.id ? 'selected' : ''}`}
                          onClick={() => setSelectedClaimId(claim.id)}
                        >
                          <td style={{ fontWeight: 700, color: 'var(--color-success)' }}>{claim.voucherNo}</td>
                          <td>{claim.billNo}</td>
                          <td style={{ fontFamily: 'monospace' }}>{claim.accountNo}</td>
                          <td>{claim.accountName}</td>
                          <td style={{ fontFamily: 'monospace' }}>{claim.challanNo}</td>
                          <td className="align-right" style={{ fontWeight: 700 }}>{fmt(claim.balance)}</td>
                          <td><span className="tcc-badge blocked"><Lock size={12} /> Refunds Blocked</span></td>
                          <td>
                            <button 
                              className="btn btn-sm btn-primary"
                              onClick={(e) => { e.stopPropagation(); setSelectedClaimId(claim.id); }}
                            >
                              Print/View Voucher
                            </button>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Voucher Render - Classic Courier Style */}
            {selectedClaim && selectedClaim.status === 'completed' && (
              <div className="animate-fade-in-up" style={{ marginTop: 'var(--space-4)' }}>
                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 'var(--space-2)', marginBottom: 'var(--space-3)' }}>
                  <button className="btn btn-secondary" onClick={() => window.print()}><Printer size={14} /> Print Voucher</button>
                  <button className="btn btn-secondary"><Download size={14} /> Download Ledger Copy</button>
                </div>

                <div className="acv-voucher">
                  <div className="acv-header">
                    <div className="acv-gov">Government of IFMIS State</div>
                    <div className="acv-office">Office of the Treasury Officer, Central District Treasury</div>
                    <div className="acv-title">ACCOUNT CLOSURE VOUCHER (PD-CF LAPSE)</div>
                  </div>

                  <div className="acv-meta-grid">
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">Voucher Number:</span>
                      <span>{selectedClaim.voucherNo}</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">Voucher Date:</span>
                      <span>{new Date().toLocaleDateString('en-IN')}</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">PD Account No:</span>
                      <span>{selectedClaim.accountNo}</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">Account Holder:</span>
                      <span>{selectedClaim.accountName} ({selectedClaim.dept})</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">By-Transfer Bill:</span>
                      <span>{selectedClaim.billNo}</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">Challan Ref No:</span>
                      <span>{selectedClaim.challanNo} (Status: Used & Consumed)</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">FD Scheme Code:</span>
                      <span>{selectedClaim.scheme}</span>
                    </div>
                    <div className="acv-meta-item">
                      <span className="acv-meta-label">Refund Capability:</span>
                      <span style={{ color: 'var(--color-error)', fontWeight: 'bold' }}>BLOCKED / LOCKED CENTRALLY</span>
                    </div>
                  </div>

                  <p style={{ fontSize: '12px', fontWeight: 600, marginBottom: 'var(--space-3)' }}>
                    Ledger Accounting Impact (By-Transfer Double-Entry Posting):
                  </p>

                  <table className="acv-ledger-table">
                    <thead>
                      <tr>
                        <th>Account Head Details</th>
                        <th>Debit (Dr) / Credit (Cr)</th>
                        <th style={{ textAlign: 'right' }}>Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {selectedClaim.originalExpHeads.map((exp, index) => (
                        <tr key={index}>
                          <td>
                            <strong>Original Exp Head: {exp.head}</strong><br />
                            <span style={{ color: 'var(--color-text-secondary)', fontSize: '10px' }}>
                              Dr. PD Account Budget-line Central Reserve
                            </span>
                          </td>
                          <td style={{ fontWeight: 'bold', color: 'var(--color-error)' }}>DEBIT (Dr)</td>
                          <td style={{ textAlign: 'right', fontWeight: 'bold' }}>{fmt(exp.amount)}</td>
                        </tr>
                      ))}
                      {selectedClaim.originalExpHeads.map((exp, index) => (
                        <tr key={`cr-${index}`}>
                          <td>
                            <strong>Receipt Head: {exp.receiptHoA === '0070' ? '0070-60-800-0000 (Central Revenue)' : exp.receiptHoA}</strong><br />
                            <span style={{ color: 'var(--color-text-secondary)', fontSize: '10px' }}>
                              Cr. Consolidated Fund Revenue Ledger
                            </span>
                          </td>
                          <td style={{ fontWeight: 'bold', color: 'var(--color-success)' }}>CREDIT (Cr)</td>
                          <td style={{ textAlign: 'right', fontWeight: 'bold' }}>{fmt(exp.amount)}</td>
                        </tr>
                      ))}
                      <tr style={{ fontWeight: 'bold', fontSize: '13px', background: 'var(--color-bg-secondary)' }}>
                        <td>Total Balanced Postings:</td>
                        <td>Balanced</td>
                        <td style={{ textAlign: 'right', textDecoration: 'underline double' }}>{fmt(selectedClaim.balance)}</td>
                      </tr>
                    </tbody>
                  </table>

                  <p style={{ fontSize: '11px', color: 'var(--color-text-secondary)', lineHeight: 1.5 }}>
                    Certified that all remaining funds in the designated budget lines under {selectedClaim.accountNo} have been transferred in full to the Consolidated Fund Receipt heads. The original PD ledger has been balanced to zero, and the account status is marked as closed. Refunds against these challans/budget-lines are blocked indefinitely.
                  </p>

                  <div className="acv-signatures">
                    <div className="acv-signature-box">
                      Treasury Officer (Creator)<br />
                      <span style={{ fontSize: '9px', color: 'var(--color-text-tertiary)' }}>Digital Signatures Verified</span>
                    </div>
                    <div className="acv-signature-box">
                      Treasury Officer (Approver)<br />
                      <span style={{ fontSize: '9px', color: 'var(--color-text-tertiary)' }}>System Authenticated</span>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ────────────────── TAB 4: NOTIFICATIONS & TIMELINES ────────────────── */}
        {activeTab === 'notifications' && (
          <div className="tcc-section animate-fade-in">
            <div className="tcc-section-header">
              <div className="tcc-section-icon"><Bell size={18} /></div>
              <h2>Treasury Notification Log & System Communications</h2>
            </div>
            
            <div className="tcc-section-body">
              <div className="tcc-info-callout info">
                <AlertCircle size={16} />
                <div>
                  System automatically coordinates communications and log audit trails between the <strong>Finance Department</strong>, 
                  <strong> Treasury Officer (Creator)</strong>, <strong>Treasury Officer (Approver)</strong>, and <strong>Deposit Admin</strong>.
                </div>
              </div>

              <div className="tcc-table-wrapper" style={{ marginTop: 'var(--space-4)' }}>
                <table className="tcc-table">
                  <thead>
                    <tr>
                      <th>Time Log</th>
                      <th>Communication Description</th>
                      <th>Target Recipients</th>
                      <th>Routing Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {logs.map(log => (
                      <tr key={log.id}>
                        <td style={{ color: 'var(--color-text-tertiary)', fontWeight: 500, fontSize: '12px' }}>{log.time}</td>
                        <td style={{ fontWeight: 500 }}>{log.text}</td>
                        <td>
                          <span className="tcc-badge draft">{log.recipient}</span>
                        </td>
                        <td>
                          {log.time === 'Pending Action' || log.time === 'Pending Approval' ? (
                            <span className="tcc-badge pending"><Clock size={10} /> Pending</span>
                          ) : (
                            <span className="tcc-badge approved"><Check size={10} /> Dispatched & Audited</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

      </div>
    </CommentLayer>
  );
}
